[package]
name = "tcp_tokio"
version = "0.1.0"
authors = ["Vlad Frolov <frolvlad@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.17"
bytes = "0.4"
bytecount = "0.5"

[profile.release]
debug = true
